[package]
name = "buildtools-assistant"
version = "0.1.0"
license = "Apache-2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.28", features = ["derive"] }
flate2 = "1.0.25"
futures = "0.3.25"
itertools = "0.10.5"
log = "0.4.17"
platform-dirs = "0.3.0"
reqwest = { version = "0.11.13", features = ["json"] }
serde = { version = "1.0.148", features = ["derive"] }
serde_json = "1.0.89"
simplelog = "0.12.0"
tar = "0.4.38"
tokio = { version = "1.22.0", features = ["full"] }
 
[profile.release]
strip = true
lto = true
